repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: mixed-line-ending
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo-fmt
        description: Check if all files follow the rustfmt style
        entry: cargo fmt -- --color always
        language: system
        pass_filenames: false
      - id: cargo-test
        name: cargo-test
        description: Check if all tests pass
        entry: cargo test
        language: system
        pass_filenames: false
