[package]
name = "aoc-2024"
version = "0.1.0"
edition = "2021"

[dependencies]
cached = "0.56.0"
clap = { version = "4.5.23", features = ["derive"] }
ndarray = { version = "0.17.0", features = ["approx"] }
rayon = "1.10.0"
regex = "1.11.1"
seq-macro = "0.3.5"
