[package]
name = "aoc-2024"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
nalgebra = "0.33.2"
ndarray = { version = "0.16.1", features = ["approx"] }
rayon = "1.10.0"
regex = "1.11.1"
seq-macro = "0.3.5"
